### ISSUE TITLE
Board of governor page : Front end changes

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitj-site#112]
Remove all the mail id's except director and chariman.. 

for chariman.. 
change the  mail id to chairman@nitj.ac.in, 
Managing Director, NIT Jalandhar... Remove NIT Jalandhar,, he is MD of SRi tools not NITJ

director@nitj.ac.in is comig to all.. remove it at all places below director...

Prof. Rajiv Kumar Garg.. Designation is missing.. "Professor" his designation

**Comment by dev-bhavya** [comment]
Made all changes
