### ISSUE TITLE
Director image size in home page

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitj-site#151]
They want the image to cover full slide.. currently it looks small.. adjust the responsiveness accordingly
![Screenshot from 2023-03-03 19-59-05](https://user-images.githubusercontent.com/88608850/222746646-37c5d79c-c927-44a8-b681-4be6b204edc2.png)

**Comment by ggsingla** [comment]
A better image of director sir is required

**Comment by harimurugan1989** [comment]
Just make changes with current image... we will get new pictures soon
