### ISSUE TITLE
Js work  for retracting sub menus in responsivenss of navbar

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitj-site#26]
We can close all the submenus when we click on the dark blue portion  of the navbar..

**Comment by ravinder-chadha** [comment]
Status: Done
Merging with next PR

**Comment by harimurugan1989** [comment]
upon clicking blue region, it is going back to home section (main navbar) but when we click same menu again it is directly going to last seen place.. not showing all the contents
