### ISSUE TITLE
Letter case in navbar

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitj-site#27]
For smaller devices, we can use only lower case letters. Only for desktop view we can use uppercase in main menu and lower case in submenus.. For other devices, we can switch to lower case.. Control this directly irrespective case from the backend. 

All menus -  Lower case for smaller screen
Main menu upper case and submenus lower in desktop view

**Comment by harimurugan1989** [comment]
@princeverma-ai please check the letter case issue in navabar.. send all the small with first letter capital... for desktop view we can hard code in front end to show it in capital..

**Comment by princeverma-ai** [comment]
its done
