### ISSUE TITLE
Design and color combination for smaller screens

### ISSUE THREAD

**Issue by harimurugan1989** [wdmc-nitj/nitj-site#28]
Use the previous shown design.. blue one is not looking good for selected menus.. may be height of menus are different,, previous one was looking good with light gray background.

Inorder to differentiate main menu and submenu, you can try different bg color(light color with blue combination) for main and submenu. Selected menu color can be different apart from this.

**Comment by ravinder-chadha** [comment]
Status: Requesting to Schedule a meeting.
Equal heights take up more space and overflow the screen in some submenus. Please confirm the final colors and design. If you want we can have a meeting anytime between 2-4 pm (IST) and I will present colour combinations. Then I'll push the final one at once.
