### ISSUE TITLE
Optimization of the Admission section pages

### ISSUE THREAD

**Issue by ggsingla** [wdmc-nitj/nitj-site#3]
### Problem related to this feature request
The pages for the different courses in the admissions section have the same content and they also have a sidebar that can toggle between the different courses available. Then what is the need for splitting the code into different pages and rewriting the same code again and again

### Purposed Solution
The different section can be toggled using the slug vale that will be added in the url for each of the course. This value can be fetched in JS and accordingly the correct UI can be rendered

### Some useful links
[How to access the url of a page in JS](https://www.tutorialrepublic.com/faq/how-to-get-the-current-url-with-javascript.php#:~:text=Answer%3A%20Use%20the%20window.,on%20click%20of%20the%20button)

[How to redirect to a Different URL with JS](https://www.developintelligence.com/blog/2016/04/javascript-redirect-how-to-redirect-a-web-page-with-javascript/#:~:text=href%20%3D%20%22https%3A%2F%2Fwww.,window%20with%20the%20new%20one)

**Comment by sushant-dhuria** [comment]
Done with this issue do check and let me know
