### ISSUE TITLE
the problem in the Alumni Navbar item on the small screen

### ISSUE THREAD

**Issue by weberankit** [wdmc-nitj/nitj-site#440]
actually on the small screen when we click on the navbar icon, a list of links opens, and when we click on any link it will direct us to a particular page or option of other links
but
after opening the nav list and when we click on the Alumni section it does not show other links rather it shows the alumni section again.
this video helps you to understand the bug--

https://user-images.githubusercontent.com/94105514/230771407-650cc6a9-7211-43cc-affd-d108c69448c2.mp4

**Comment by weberankit** [comment]
I am going to work on it plz assigned it to  me so that I can start working

**Comment by harimurugan1989** [comment]
> I am going to work on it plz assigned it to  me so that I can start working

We have assigned it to front end team. Thanks for finding the bug. 

If you want to work with us. Contact Nisha mam.

**Comment by harimurugan1989** [comment]
> I am going to work on it plz assigned it to  me so that I can start working

It's not an bug. It's designed that way.

**Comment by weberankit** [comment]
maybe but that needs to be changed as when the user clicks on the alumni section it should direct it to other links, not to the same link
I can fix it and I have already installed this repository on my local host
sorry I don't know Nisha Mam, I'm contributing to this project as I found this repository on GitHub explore.
![image](https://user-images.githubusercontent.com/94105514/230772033-8d1361df-07e1-4b65-a2b7-30d1e619e96b.png)

**Comment by weberankit** [comment]
I think you have deleted  the above discussion section where you mentioned that I have to contact Nisha mam for contribution to this project, If it is for the contribution of a particular member then plz plz make this repository private and invite a collaborator to contribute because **people like me investing their 2-3 hrs time to set up the project and after installing project and finding issue we come to know that we have to contact this that person to contribute its not right hope you understand it** 

otherwise in readme section mention there only specific people can contribute
I'm just requesting you to do this Hope you understand

**Comment by weberankit** [comment]
Could you plz tell me how can I contact Nisha mam
